languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "David Haven"
# logo = "img/logo.png"
description = "David Haven's personal website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "David Haven"
  image = "img/logo-dhaven.png"
  headline = "Enjoying life one day at a time"
  bio = "Systems, open source"
  links = [
     { github = "https://github.com/dhaven" },
     { linkedin = "https://linkedin.com/in/david-haven" },
  ]
